/**
 * Generate Encryption Key
 * One-time use function to generate a new AES-256 encryption key
 * 
 * SECURITY: This function should only be accessible to superadmin
 * After generating the key, add it to Supabase secrets and disable this function
 */

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { generateEncryptionKey } from '../_shared/encryption.ts';
import { logSecurityEvent } from '../_shared/audit.ts';
import { SecuritySeverity, SecurityEventType } from '../_shared/constants.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    // Get environment variables
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    
    // Check if function is disabled
    const functionDisabled = Deno.env.get('DISABLE_KEY_GENERATION') === 'true';
    if (functionDisabled) {
      return new Response(
        JSON.stringify({ 
          success: false, 
          message: 'Key generation is disabled for security' 
        }),
        { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Get authorization header
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(
        JSON.stringify({ success: false, message: 'Unauthorized' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Initialize Supabase client
    const supabase = createClient(supabaseUrl, supabaseServiceKey, {
      global: {
        headers: { Authorization: authHeader },
      },
    });

    // Get authenticated user
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return new Response(
        JSON.stringify({ success: false, message: 'Unauthorized' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Check if user is superadmin
    const { data: userData, error: userError } = await supabase
      .from('users')
      .select('role')
      .eq('id', user.id)
      .single();

    if (userError || !userData || userData.role !== 'superadmin') {
      await logSecurityEvent(supabase, {
        event_type: SecurityEventType.UNAUTHORIZED_ACCESS,
        severity: SecuritySeverity.HIGH,
        user_id: user.id,
        endpoint: '/generate-encryption-key',
        details: {
          reason: 'Non-superadmin attempted to generate encryption key',
        },
      });

      return new Response(
        JSON.stringify({ success: false, message: 'Forbidden' }),
        { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Generate new encryption key
    const newKey = generateEncryptionKey();

    // Log key generation
    await logSecurityEvent(supabase, {
      event_type: SecurityEventType.ENCRYPTION_KEY_ACCESS,
      severity: SecuritySeverity.CRITICAL,
      user_id: user.id,
      endpoint: '/generate-encryption-key',
      details: {
        action: 'Key generated',
        timestamp: new Date().toISOString(),
      },
    });

    console.log('🔑 New encryption key generated by superadmin:', user.id);

    // Return the key (ONLY ONCE - save it immediately!)
    return new Response(
      JSON.stringify({
        success: true,
        key: newKey,
        instructions: [
          '1. Copy this key immediately - it will not be shown again',
          '2. Add to Supabase secrets: ENCRYPTION_MASTER_KEY',
          '3. Set DISABLE_KEY_GENERATION=true to disable this function',
          '4. Never commit this key to version control',
          '5. Store backup in secure password manager',
        ],
      }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('❌ Error generating key:', error);
    return new Response(
      JSON.stringify({
        success: false,
        message: 'Internal server error',
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
